=== lasalesi/HostingChecker/HostingCheckerCommons/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="config"
    targetNamespace="https://libracore.com/xml/HostingChecker/config.xsd"
    elementFormDefault="qualified"
    xmlns="https://libracore.com/xml/HostingChecker/config.xsd"
    xmlns:mstns="https://libracore.com/xml/HostingChecker/config.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:element name="Configuration">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="Domains">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Resource" minOccurs="0" maxOccurs="200">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string" />
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
          
        <xs:element name="Server" type="xs:string" />
        <xs:element name="Port" type="xs:integer" />
        <xs:element name="Username" type="xs:string" />
        <xs:element name="Password" type="xs:string" />
        <xs:element name="Schema" type="xs:string" />
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lasalesi/HostingChecker/HostingCheckerCommons/config_sample.xml
<?xml version="1.0" encoding="utf-8" ?>
<Configuration xmlns="https://libracore.com/xml/HostingChecker/config.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://libracore.com/xml/HostingChecker/config.xsd config.xsd">
  <!-- Domain resources to check-->
  <Domains>
    <Resource>http://www.exmaple.com</Resource>
  </Domains>

  <!-- Statistics MySQL server -->
  <Server>localhost</Server>
  <Port>3306</Port>
  <Username>hostingchecker</Username>
  <Password>hostingchecker123</Password>
  <Schema>hostingchecker</Schema>
</Configuration>
